export const PATHS = {
  HOME: '/',
  AUTH: {
    WELCOME: '/auth/welcome',
    LOGIN: '/auth/login',
    ADMIN_LOGIN: '/auth/admin-login',
    REGISTER: '/auth/register',
    ROLE_SELECTION: '/auth/role-selection',
    OTP_VERIFICATION: '/auth/verify-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  ADMIN: {
    ROOT: '/admin',
    OVERVIEW: '/admin',
    FARMERS: '/admin/farmers',
    INSURANCE: {
      COMPANIES: '/admin/insurance/companies',
      OFFICERS: '/admin/insurance/officers',
    },
    POLICIES: '/admin/policies',
    CLAIMS: '/admin/claims',
    CLAIM_DETAIL: (id: string) => `/admin/claims/${id}`,
    FRAUD: '/admin/fraud',
    ANALYTICS: '/admin/analytics',
    NOTIFICATIONS: '/admin/notifications',
    AUDIT_LOGS: '/admin/audit-logs',
    SETTINGS: '/admin/settings',
    PROFILE: '/admin/profile',
  },
  FARMER: {
    ROOT: '/farmer',
    OVERVIEW: '/farmer',
    BROWSE: '/farmer/browse',
    SUBMIT_CLAIM: '/farmer/submit-claim',
    POLICIES: '/farmer/policies',
    TRANSACTIONS: '/farmer/transactions',
    VOICE_ASSISTANT: '/farmer/voice-assistant',
    SETTINGS: '/farmer/settings',
  },
  INSURANCE: {
    ROOT: '/insurance',
    OVERVIEW: '/insurance',
    CLAIMS: '/insurance/claims',
    FARMERS: '/insurance/farmers',
    POLICIES: '/insurance/policies',
    SETTINGS: '/insurance/settings',
  },
  DASHBOARD: {
    FARMER: '/farmer',
    farmer: '/farmer',
    INSURANCE_COMPANY: '/insurance',
    insurance_company: '/insurance',
    ADMIN: '/admin',
    admin: '/admin',
    WARD_OFFICIAL: '/ward',
    ward_official: '/ward',
    INSURANCE_AGENT: '/agent',
    insurance_agent: '/agent',
    INSURANCE_OFFICER: '/insurance',
    INSURANCE: '/insurance',
  },
} as const;
